var searchData=
[
  ['va_5flist_2177',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray_2178',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std::valarray'],['http://en.cppreference.com/w/cpp/header/valarray.html',1,'(Global Namespace)']]],
  ['valid_2179',['valid',['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()'],['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()']]],
  ['validate_5fname_2180',['validate_name',['../classemail_1_1NamedObject.html#ab2b95bd3169bcecfbda7002cbf3c8586',1,'email::NamedObject']]],
  ['value_2181',['value',['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()'],['http://en.cppreference.com/w/cpp/utility/optional/value.html',1,'std::optional::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['../classemail_1_1Gid.html#aa4ac19221b7be24f6ff62aeb60d44cf2',1,'email::Gid::value()']]],
  ['value_5fcomp_2182',['value_comp',['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::pmr::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::pmr::multimap::value_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::pmr::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::pmr::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()']]],
  ['value_5fcompare_2183',['value_compare',['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::pmr::map::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::multimap::value_compare'],['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::map::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::pmr::multimap::value_compare']]],
  ['value_5for_2184',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional::value_or()'],['http://en.cppreference.com/w/cpp/utility/optional/value_or.html',1,'std::optional::value_or()']]],
  ['valueless_5fby_5fexception_2185',['valueless_by_exception',['http://en.cppreference.com/w/cpp/utility/variant/valueless_by_exception.html',1,'std::variant']]],
  ['variant_2186',['variant',['http://en.cppreference.com/w/cpp/utility/variant.html',1,'std::variant'],['http://en.cppreference.com/w/cpp/header/variant.html',1,'(Global Namespace)'],['http://en.cppreference.com/w/cpp/utility/variant/variant.html',1,'std::variant::variant()']]],
  ['variant_5falternative_2187',['variant_alternative',['http://en.cppreference.com/w/cpp/utility/variant/variant_alternative.html',1,'std']]],
  ['variant_5falternative_5ft_2188',['variant_alternative_t',['http://en.cppreference.com/w/cpp/utility/variant/variant_alternative.html',1,'std']]],
  ['variant_5fsize_2189',['variant_size',['http://en.cppreference.com/w/cpp/utility/variant/variant_size.html',1,'std']]],
  ['variant_5fsize_5fv_2190',['variant_size_v',['http://en.cppreference.com/w/cpp/utility/variant/variant_size.html',1,'std']]],
  ['vector_2191',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std::pmr::vector'],['http://en.cppreference.com/w/cpp/container/vector.html',1,'std::vector'],['http://en.cppreference.com/w/cpp/header/vector.html',1,'(Global Namespace)'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::pmr::vector::vector()'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector::vector()']]],
  ['vector_3c_20email_3a_3aguardcondition_20_2a_20_3e_2192',['vector&lt; email::GuardCondition * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20email_3a_3aserviceclient_20_2a_20_3e_2193',['vector&lt; email::ServiceClient * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20email_3a_3aserviceserver_20_2a_20_3e_2194',['vector&lt; email::ServiceServer * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20email_3a_3asubscription_20_2a_20_3e_2195',['vector&lt; email::Subscription * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3afunction_20_3e_2196',['vector&lt; std::function &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3astring_20_3e_2197',['vector&lt; std::string &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['version_2198',['version',['http://en.cppreference.com/w/cpp/header/version.html',1,'']]],
  ['vfprintf_2199',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf_2200',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf_2201',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf_2202',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['visibility_5fcontrol_2ehpp_2203',['visibility_control.hpp',['../visibility__control_8hpp.html',1,'']]],
  ['visit_2204',['visit',['http://en.cppreference.com/w/cpp/utility/variant/visit.html',1,'std']]],
  ['void_5ft_2205',['void_t',['http://en.cppreference.com/w/cpp/types/void_t.html',1,'std']]],
  ['vprintf_2206',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf_2207',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf_2208',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf_2209',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf_2210',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf_2211',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf_2212',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf_2213',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf_2214',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
