var searchData=
[
  ['safemap_3061',['SafeMap',['../classemail_1_1SafeMap.html',1,'email']]],
  ['safequeue_3062',['SafeQueue',['../classemail_1_1SafeQueue.html',1,'email']]],
  ['safequeue_3c_20struct_20email_3a_3aemaildata_20_3e_3063',['SafeQueue&lt; struct email::EmailData &gt;',['../classemail_1_1SafeQueue.html',1,'email']]],
  ['scoped_5fallocator_5fadaptor_3064',['scoped_allocator_adaptor',['http://en.cppreference.com/w/cpp/memory/scoped_allocator_adaptor.html',1,'std']]],
  ['seconds_3065',['seconds',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['seed_5fseq_3066',['seed_seq',['http://en.cppreference.com/w/cpp/numeric/random/seed_seq.html',1,'std']]],
  ['sentry_3067',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::iostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_ifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::osyncstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wistream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wosyncstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::ifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_istream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::fstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_istringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wiostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_stringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_fstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_iostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::stringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wistringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_osyncstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::strstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostrstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wstringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wfstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istrstream::sentry']]],
  ['sequenced_5fpolicy_3068',['sequenced_policy',['http://en.cppreference.com/w/cpp/algorithm/execution_policy_tag_t.html',1,'std::execution']]],
  ['serviceclient_3069',['ServiceClient',['../classemail_1_1ServiceClient.html',1,'email']]],
  ['servicehandler_3070',['ServiceHandler',['../classemail_1_1ServiceHandler.html',1,'email']]],
  ['serviceinfo_3071',['ServiceInfo',['../classemail_1_1ServiceInfo.html',1,'email']]],
  ['servicenameinvaliderror_3072',['ServiceNameInvalidError',['../classemail_1_1ServiceNameInvalidError.html',1,'email']]],
  ['serviceobject_3073',['ServiceObject',['../classemail_1_1ServiceObject.html',1,'email']]],
  ['servicerequest_3074',['ServiceRequest',['../structemail_1_1ServiceRequest.html',1,'email']]],
  ['servicerequestid_3075',['ServiceRequestId',['../structemail_1_1ServiceRequestId.html',1,'email']]],
  ['serviceserver_3076',['ServiceServer',['../classemail_1_1ServiceServer.html',1,'email']]],
  ['set_3077',['set',['http://en.cppreference.com/w/cpp/container/set.html',1,'std::pmr::set'],['http://en.cppreference.com/w/cpp/container/set.html',1,'std::set']]],
  ['shared_5ffuture_3078',['shared_future',['http://en.cppreference.com/w/cpp/thread/shared_future.html',1,'std']]],
  ['shared_5flock_3079',['shared_lock',['http://en.cppreference.com/w/cpp/thread/shared_lock.html',1,'std']]],
  ['shared_5fmutex_3080',['shared_mutex',['http://en.cppreference.com/w/cpp/thread/shared_mutex.html',1,'std']]],
  ['shared_5fptr_3081',['shared_ptr',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20email_3a_3aemailreceiver_20_3e_3082',['shared_ptr&lt; email::EmailReceiver &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20email_3a_3aemailsender_20_3e_3083',['shared_ptr&lt; email::EmailSender &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20email_3a_3aintraemailreceiver_20_3e_3084',['shared_ptr&lt; email::IntraEmailReceiver &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20email_3a_3aoptions_20_3e_3085',['shared_ptr&lt; email::Options &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20email_3a_3apollingmanager_20_3e_3086',['shared_ptr&lt; email::PollingManager &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20email_3a_3aservicehandler_20_3e_3087',['shared_ptr&lt; email::ServiceHandler &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20email_3a_3asubscriptionhandler_20_3e_3088',['shared_ptr&lt; email::SubscriptionHandler &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20logger_20_3e_3089',['shared_ptr&lt; Logger &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5ftimed_5fmutex_3090',['shared_timed_mutex',['http://en.cppreference.com/w/cpp/thread/shared_timed_mutex.html',1,'std']]],
  ['shuffle_5forder_5fengine_3091',['shuffle_order_engine',['http://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine.html',1,'std']]],
  ['sig_5fatomic_5ft_3092',['sig_atomic_t',['http://en.cppreference.com/w/cpp/utility/program/sig_atomic_t.html',1,'std']]],
  ['size_5ft_3093',['size_t',['http://en.cppreference.com/w/cpp/types/size_t.html',1,'std']]],
  ['slice_3094',['slice',['http://en.cppreference.com/w/cpp/numeric/valarray/slice.html',1,'std']]],
  ['slice_5farray_3095',['slice_array',['http://en.cppreference.com/w/cpp/numeric/valarray/slice_array.html',1,'std']]],
  ['smatch_3096',['smatch',['http://en.cppreference.com/w/cpp/regex/match_results.html',1,'std']]],
  ['source_5flocation_3097',['source_location',['http://en.cppreference.com/w/cpp/experimental/source_location.html',1,'std::experimental']]],
  ['space_5finfo_3098',['space_info',['http://en.cppreference.com/w/cpp/experimental/fs/space_info.html',1,'std::experimental::filesystem::space_info'],['http://en.cppreference.com/w/cpp/filesystem/space_info.html',1,'std::filesystem::space_info']]],
  ['span_3099',['span',['http://en.cppreference.com/w/cpp/container/span.html',1,'std']]],
  ['sregex_5fiterator_3100',['sregex_iterator',['http://en.cppreference.com/w/cpp/regex/regex_iterator.html',1,'std']]],
  ['sregex_5ftoken_5fiterator_3101',['sregex_token_iterator',['http://en.cppreference.com/w/cpp/regex/regex_token_iterator.html',1,'std']]],
  ['ssub_5fmatch_3102',['ssub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['stack_3103',['stack',['http://en.cppreference.com/w/cpp/container/stack.html',1,'std']]],
  ['state_5ftype_3104',['state_type',['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_byname::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf8::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf8_utf16::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf16::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt::state_type']]],
  ['steady_5fclock_3105',['steady_clock',['http://en.cppreference.com/w/cpp/chrono/steady_clock.html',1,'std::chrono']]],
  ['streambuf_3106',['streambuf',['http://en.cppreference.com/w/cpp/io/basic_streambuf.html',1,'std']]],
  ['streamoff_3107',['streamoff',['http://en.cppreference.com/w/cpp/io/streamoff.html',1,'std']]],
  ['streampos_3108',['streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['streamsize_3109',['streamsize',['http://en.cppreference.com/w/cpp/io/streamsize.html',1,'std']]],
  ['string_3110',['string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::string'],['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::pmr::string']]],
  ['string_5ftype_3111',['string_type',['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'std::moneypunct::string_type'],['http://en.cppreference.com/w/cpp/locale/money_get.html',1,'std::money_get::string_type'],['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std::numpunct_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std::numpunct::string_type'],['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'std::moneypunct_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std::collate::string_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std::collate_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'std::messages::string_type'],['http://en.cppreference.com/w/cpp/locale/money_put.html',1,'std::money_put::string_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'std::messages_byname::string_type']]],
  ['string_5fview_3112',['string_view',['http://en.cppreference.com/w/cpp/experimental/basic_string_view.html',1,'std::experimental::string_view'],['http://en.cppreference.com/w/cpp/string/basic_string_view.html',1,'std::string_view']]],
  ['stringbuf_3113',['stringbuf',['http://en.cppreference.com/w/cpp/io/basic_stringbuf.html',1,'std']]],
  ['stringstream_3114',['stringstream',['http://en.cppreference.com/w/cpp/io/basic_stringstream.html',1,'std']]],
  ['strong_5fequality_3115',['strong_equality',['http://en.cppreference.com/w/cpp/utility/compare/strong_equality.html',1,'std']]],
  ['strong_5fordering_3116',['strong_ordering',['http://en.cppreference.com/w/cpp/utility/compare/strong_ordering.html',1,'std']]],
  ['strstream_3117',['strstream',['http://en.cppreference.com/w/cpp/io/strstream.html',1,'std']]],
  ['strstreambuf_3118',['strstreambuf',['http://en.cppreference.com/w/cpp/io/strstreambuf.html',1,'std']]],
  ['student_5ft_5fdistribution_3119',['student_t_distribution',['http://en.cppreference.com/w/cpp/numeric/random/student_t_distribution.html',1,'std']]],
  ['sub_5fmatch_3120',['sub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['subscription_3121',['Subscription',['../classemail_1_1Subscription.html',1,'email']]],
  ['subscriptionhandler_3122',['SubscriptionHandler',['../classemail_1_1SubscriptionHandler.html',1,'email']]],
  ['subtract_5fwith_5fcarry_5fengine_3123',['subtract_with_carry_engine',['http://en.cppreference.com/w/cpp/numeric/random/subtract_with_carry_engine.html',1,'std']]],
  ['syncbuf_3124',['syncbuf',['http://en.cppreference.com/w/cpp/io/basic_syncbuf.html',1,'std']]],
  ['synchronized_5fpool_5fresource_3125',['synchronized_pool_resource',['http://en.cppreference.com/w/cpp/experimental/synchronized_pool_resource.html',1,'std::experimental::pmr::synchronized_pool_resource'],['http://en.cppreference.com/w/cpp/memory/synchronized_pool_resource.html',1,'std::pmr::synchronized_pool_resource']]],
  ['system_5fclock_3126',['system_clock',['http://en.cppreference.com/w/cpp/chrono/system_clock.html',1,'std::chrono']]],
  ['system_5ferror_3127',['system_error',['http://en.cppreference.com/w/cpp/error/system_error.html',1,'std']]]
];
