name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: "Build and test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
    # - name: "Install (lib)curl"
    #   run: |
    #     choco install --limit-output --no-progress --yes curl
    #   if: matrix.os == 'windows-latest'
    - uses: ros-tooling/action-ros-ci@master
      with:
        package-name: rosidl_default_generators unique_identifier_msgs
        target-ros2-distro: rolling
        vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
        import-token: ${{ secrets.REPO_TOKEN }}
        colcon-defaults: |
          {
            "build": {
              "mixin": [
                  "coverage-gcc"
              ]
            }
          }
    - uses: codecov/codecov-action@v1
      with:
        file: ros_ws/lcov/total_coverage.info
        flags: unittests
        name: codecov-umbrella
