name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: "Build and test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
      with:
        required-ros-distributions: ${{ matrix.os == 'windows-latest' && '' || 'rolling' }}
    - name: "Install (lib)curl"
      run: |
        choco install --limit-output --no-progress --yes curl
      if: matrix.os == 'windows-latest'
    - uses: ros-tooling/action-ros-ci@master
      with:
        package-name: email
        target-ros2-distro: rolling
        vcs-repo-file-url: ${{ matrix.os == 'windows-latest' && 'https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos' || '' }}
        import-token: ${{ secrets.REPO_TOKEN }}
        colcon-defaults: |
          {
            "build": {
              "mixin": [
                  "coverage-gcc"
              ]
            }
          }
    - uses: codecov/codecov-action@v1
      with:
        file: ros_ws/lcov/total_coverage.info
        flags: unittests
        name: codecov-umbrella
