name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
    - uses: christophebedard/action-ros-ci@automatically-allow-accessing-private-deps-repo-files
      with:
        package-name: email
        target-ros2-distro: rolling
        import-token: ${{ secrets.REPO_TOKEN }}
        colcon-mixin-name: coverage-gcc coverage-pytest
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ros_ws/lcov/total_coverage.info
        flags: unittests
        name: codecov-umbrella
