name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: "Build and test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build-type: binary
          - os: ubuntu-latest
            build-type: source
          # - os: macos-latest
          #   build-type: source
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
      with:
        required-ros-distributions: ${{ matrix.build-type == 'binary' && 'rolling' || '' }}
    - uses: ros-tooling/action-ros-ci@master
      with:
        package-name: email email_examples rmw_email_cpp
        target-ros2-distro: rolling
        vcs-repo-file-url: |
          ${{ github.workspace }}/dependencies.repos
          ${{ matrix.build-type == 'source' && 'https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos' || '' }}
        import-token: ${{ secrets.REPO_TOKEN }}
        colcon-defaults: |
          {
            "build": {
              "mixin": [
                  "coverage-gcc"
              ]
            }
          }
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ros_ws/lcov/total_coverage.info
        flags: unittests
        name: codecov-umbrella
