name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
    - uses: ros-tooling/action-ros-ci@master
      with:
        package-name: email
        target-ros2-distro: rolling
        vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
        import-token: ${{ secrets.REPO_TOKEN }}
        colcon-defaults: |
          {
            "build": {
              "mixin": [
                  "coverage-gcc",
                  "coverage-pytest"
              ]
            },
            "test": {
              "mixin": [
                "coverage-pytest"
              ]
            }
          }
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ros_ws/lcov/total_coverage.info
        flags: unittests
        name: codecov-umbrella
