name: Documentation
on:
  push:
    branches:
      - rolling
jobs:
  docs_gen:
    name: "Generate and push"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen pandoc plantuml
        pip3 install pandoc-plantuml-filter
        wget https://github.com/plantuml/plantuml/releases/download/v1.2023.5/plantuml-1.2023.5.jar
        chmod +x plantuml-*.jar
    - name: Install rosdoc2
      run: |
        pip3 install -U git+https://github.com/ros-infrastructure/rosdoc2.git@main
    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        fetch-depth: 0
        path: gh-pages/
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: rolling
        fetch-depth: 0
        path: rmw_email
    - name: Gen API docs
      run: |
        rosdoc2 build --package-path rmw_email/email/
    - name: Gen design docs
      run: |
        mkdir -p pandoc/email/ && cd pandoc/email/
        sed -i '/christophebedard.com/d' ../../rmw_email/email/doc/design.md
        PLANTUML_BIN="$(pwd)/../../plantuml-1.2023.5.jar" pandoc ../../rmw_email/email/doc/design.md --filter pandoc-plantuml > index.html
    - name: Copy docs to gh-pages
      run: |
        rm -rf gh-pages/api/
        mv docs_output/ gh-pages/api/
        rm -rf gh-pages/design/
        mv -T pandoc/ gh-pages/design/
    - name: Commit and push to gh-pages branch
      run: |
        cd gh-pages
        git config --global user.email "3717345+christophebedard@users.noreply.github.com"
        git config --global user.name "Christophe Bedard [bot]"
        git add .
        git commit -m "Update docs"
        git push origin gh-pages
