name: Documentation
on:
  push:
    branches:
      - rolling
jobs:
  docs_gen:
    name: "Generate and push"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen pandoc plantuml
        pip3 install pandoc-plantuml-filter
    - name: Get gen_docs
      uses: actions/checkout@v3
      with:
        repository: christophebedard/gen_docs
        ref: master
        fetch-depth: 0
        path: gen_docs/
    - name: Install gen_docs dependencies
      run: |
        pip3 install -r gen_docs/requirements.txt
    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        fetch-depth: 0
        path: gh-pages/
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: rolling
        fetch-depth: 0
        path: repos/rolling/
    - name: Gen API docs
      run: |
        python3 gen_docs/gen_docs.py --config gh-pages/gen_docs.yml --skip-clone
    - name: Gen design docs
      run: |
        mkdir -p pandoc/email/ && cd pandoc/email/
        sed -i '/christophebedard.com/d' ../../repos/rolling/email/doc/design.md
        pandoc ../../repos/rolling/email/doc/design.md --filter pandoc-plantuml > index.html
    - name: Copy docs to gh-pages
      run: |
        rm -rf gh-pages/api/
        mv -T output/rolling/ gh-pages/api/
        rm -rf gh-pages/design/
        mv -T pandoc/ gh-pages/design/
    - name: Commit and push to gh-pages branch
      run: |
        cd gh-pages
        git config --global user.email "3717345+christophebedard@users.noreply.github.com"
        git config --global user.name "Christophe Bedard [bot]"
        git add .
        git commit -m "Update docs"
        git push origin gh-pages
