name: Tag
on:
  push:
    branches:
      - rolling
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: christophebedard/tag-version-commit@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version_assertion_command: 'grep -q "<version>$version</version>" email/package.xml && grep -q "<version>$version</version>" email_examples/package.xml && grep -q "<version>$version</version>" rmw_email_cpp/package.xml'
